/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check application and database health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/site": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the public site descriptor
         * @description Public endpoint without authentication. It returns only the site name
         *     and the registration switch; no other settings keys are exposed.
         *     The site name defaults to `ImgNest` until a configured name exists.
         */
        get: operations["getSite"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the rules the authenticated user may upload through
         * @description Returns the enabled rules bound to the authenticated user's group whose
         *     storage backend is enabled, ordered by ID — the same grant semantics
         *     the upload endpoint enforces, so every listed rule is acceptable to
         *     upload. A group without eligible bindings yields data `[]`, never null.
         */
        get: operations["listPolicies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register an ordinary user
         * @description Registration must be enabled by the site administrator. The server
         *     assigns role `user` and the default group; clients cannot set role,
         *     group_id, or other account attributes. Limited to three requests
         *     per minute per client IP, independently of the login limit.
         */
        post: operations["registerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in and issue a web token
         * @description A successful login issues a web token that expires in 24 hours.
         *     Copy the token from this response; it cannot be retrieved later.
         *     Limited to three requests per minute per client IP, independently
         *     of the registration limit. Disabled users cannot log in.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated user */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke the current bearer token
         * @description Other tokens belonging to the user remain active.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change the password and revoke all user tokens
         * @description Requires the current password. A successful change revokes every
         *     token owned by the user, including the token used for this request.
         *     Log in again with the new password to obtain a new web token.
         */
        patch: operations["changePassword"];
        trace?: never;
    };
    "/api/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the authenticated user's token metadata
         * @description Returns an array of TokenView objects. An empty list has data `[]`.
         *     The plaintext secret and token hash are never included.
         */
        get: operations["listTokens"];
        put?: never;
        /**
         * Create an API token
         * @description The server assigns kind `api` and abilities `["*"]`. These fields
         *     cannot be provided by clients in M1. The expiry may be omitted or
         *     null for an API token without an expiry; otherwise it must be later
         *     than the current time. The plaintext token is returned only once.
         */
        post: operations["createToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tokens/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke an owned token
         * @description A token belonging to another user and a nonexistent token both
         *     return 403 with code 20003 to avoid disclosing token ownership.
         */
        delete: operations["revokeToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload one or more images with independent compensation
         * @description Requires a valid bearer token. Authentication and default-group upload
         *     preflight happen before the request body is read. Multipart parts are
         *     read into bounded memory; source images are never spooled to temporary
         *     files. Metadata fields may occur before or after file parts, but may
         *     not be repeated. Unknown fields are rejected. The selected policy is
         *     checked again before processing. Real image format is detected from
         *     bytes by the shared image service, not from filenames or Content-Type.
         *     Defaults: 64 MiB total request, at most 20 files, two concurrent upload
         *     requests, five-minute request deadline. Group and deployment file caps
         *     also apply. File-level failures do not roll back successful siblings.
         *     A single file returns its ImageView with HTTP 201 or a normal error;
         *     multiple files return HTTP 207 with one result per file, in input order.
         */
        post: operations["uploadImages"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the authenticated user's active images */
        get: operations["listImages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Authenticated native numeric image identifier. */
                id: components["parameters"]["ImageID"];
            };
            cookie?: never;
        };
        /** Read an owner-authorized image */
        get: operations["getImage"];
        put?: never;
        post?: never;
        /**
         * Move an image into the recycle bin
         * @description Successful completion removes the original keys from the origin; CDN cache purging is outside this contract.
         */
        delete: operations["trashImage"];
        options?: never;
        head?: never;
        /**
         * Change public-list visibility
         * @description Private images remain accessible to anyone holding their direct object link.
         */
        patch: operations["setImageVisibility"];
        trace?: never;
    };
    "/api/images/{id}/exif": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read full owner/admin metadata, including GPS
         * @description This authenticated endpoint is the only image API returning GPS and raw metadata.
         */
        get: operations["getImageExif"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete images or change their visibility individually */
        post: operations["batchImages"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trash": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the authenticated user's recycle bin */
        get: operations["listTrash"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trash/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore selected images to their original paths
         * @description Authorization and current capacity are rechecked before activation.
         */
        post: operations["restoreImages"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trash/purge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Permanently remove selected trashed images
         * @description Removes owned object history and deletion markers before releasing the image path reservation.
         */
        post: operations["purgeImages"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/i/{storageID}/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storageID: components["schemas"]["ID"];
                /** @description Canonical object key, possibly containing slash-separated path segments, with its extension. */
                key: string;
            };
            cookie?: never;
        };
        /**
         * Read an active local object using its direct link
         * @description Private display visibility does not restrict direct links. Pending, deleted, and undeclared objects return 404.
         */
        get: operations["getLocalImageObject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /** Read local-object headers without its body */
        head: operations["headLocalImageObject"];
        patch?: never;
        trace?: never;
    };
    "/t/{key}.webp": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable opaque image key, excluding the .webp suffix. */
                key: string;
            };
            cookie?: never;
        };
        /**
         * Read or lazily refill the local thumbnail cache
         * @description Public thumbnails allow anonymous requests. Private thumbnails require the owner or an administrator. A supplied invalid Bearer token is rejected.
         */
        get: operations["getImageThumbnail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /** Read authorized thumbnail headers without its body */
        head: operations["headImageThumbnail"];
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ImageIDs: components["schemas"]["ID"][];
        ImageLinks: {
            /** @description Preferred available version. */
            url: string;
            /** @description Empty if no original is stored. */
            original: string;
            /** @description Empty if no WebP is stored. */
            webp: string;
            /** @description Cloud thumbnail URL or an empty string. */
            thumbnail_url: string;
        };
        /** @description Safe image metadata; never contains EXIF, GPS, source IP, provider credentials, or operation internals. */
        ImageView: {
            id: components["schemas"]["ID"];
            /** @description Stable opaque public image identity. */
            key: string;
            user_id: components["schemas"]["ID"];
            /**
             * Format: int64
             * @description Zero when no album is selected.
             */
            album_id: number;
            policy_id: components["schemas"]["ID"];
            storage_id: components["schemas"]["ID"];
            /** @description Original client filename; not used for format detection. */
            name: string;
            ext: string;
            mime: string;
            /**
             * Format: int64
             * @description Stored primary-object bytes.
             */
            size: number;
            /** Format: int64 */
            webp_size: number;
            /**
             * Format: int64
             * @description Unique cloud-object bytes including cloud thumbnail; excludes local cache.
             */
            charged_bytes: number;
            width: number;
            height: number;
            frames: number;
            has_original: boolean;
            has_webp: boolean;
            has_thumb: boolean;
            scrubbed: boolean;
            /** @description Controls display visibility; direct links remain accessible. */
            is_public: boolean;
            /** @description MD5 of the stored primary object's exact bytes. */
            md5: string;
            /** @description SHA-1 of the stored primary object's exact bytes. */
            sha1: string;
            /** @description MD5 of the original uploaded bytes before sanitization. */
            src_md5: string;
            links: components["schemas"]["ImageLinks"];
            local_thumb_url: string;
            deleted_at: components["schemas"]["NullableTimestamp"];
            purge_at: components["schemas"]["NullableTimestamp"];
            created_at: components["schemas"]["Timestamp"];
        };
        ImagePage: {
            items: components["schemas"]["ImageView"][];
            /** Format: int64 */
            total: number;
            page: number;
            size: number;
        };
        ImageExif: {
            image_id: components["schemas"]["ID"];
            make: string;
            model: string;
            lens: string;
            exposure: string;
            f_number: string;
            focal_length: string;
            iso: number;
            orientation: number;
            taken_at: components["schemas"]["NullableTimestamp"];
            gps_lat: number | null;
            gps_lng: number | null;
            gps_alt: number | null;
            /** @description Complete private metadata archive */
            raw: {
                [key: string]: unknown;
            };
            created_at: components["schemas"]["Timestamp"];
            updated_at: components["schemas"]["Timestamp"];
        };
        ImageBatchItem: {
            id?: components["schemas"]["ID"];
            /** @description Present for upload results. */
            filename?: string;
            /** @description HTTP-equivalent status for this item. */
            status: number;
            /** @description Zero on success; otherwise an application error code. */
            code: number;
            message: string;
            /** @description ImageView for successful uploads/visibility updates; null for deletion/restoration/purge or failures. */
            data: components["schemas"]["ImageView"] | components["schemas"]["NullData"];
        };
        ImageEnvelope: components["schemas"]["SuccessEnvelope"] & {
            data?: components["schemas"]["ImageView"];
        };
        ImagePageEnvelope: components["schemas"]["SuccessEnvelope"] & {
            data?: components["schemas"]["ImagePage"];
        };
        ImageExifEnvelope: components["schemas"]["SuccessEnvelope"] & {
            data?: components["schemas"]["ImageExif"];
        };
        ImageBatchEnvelope: components["schemas"]["SuccessEnvelope"] & {
            data?: components["schemas"]["ImageBatchItem"][];
        };
        /**
         * Format: int64
         * @description Positive signed BIGINT database identifier, serialized as a JSON number.
         * @example 7
         */
        ID: number;
        /**
         * Format: date-time
         * @description UTC RFC3339 timestamp; fractional seconds may be present.
         * @example 2026-10-04T00:00:00Z
         */
        Timestamp: string;
        /**
         * Format: date-time
         * @description UTC RFC3339 timestamp, or null when unset.
         * @example null
         */
        NullableTimestamp: string | null;
        /**
         * Format: password
         * @description New password length is 12–72 UTF-8 bytes, not characters or runes.
         *     Whitespace is part of the password and is not trimmed. The byte
         *     limits are enforced by the service; OpenAPI minLength/maxLength
         *     would count characters and therefore are not used here.
         */
        Password: string;
        /**
         * Format: password
         * @description Existing password for login or current-password verification.
         *     Accepts 1–72 UTF-8 bytes so legacy bcrypt credentials below the
         *     new-password minimum remain usable. Whitespace is not trimmed.
         *     The upper limit counts bytes, so maxLength is not used here.
         */
        CredentialPassword: string;
        /**
         * @description Plain email address. Surrounding whitespace is trimmed and the
         *     address is lowercased before validation. Display-name forms such
         *     as `Name <user@example.com>` are rejected.
         * @example user@example.com
         */
        EmailInput: string;
        /**
         * @description Newly issued bearer credential. Its ID is a positive signed BIGINT
         *     database identifier and its secret is exactly 40 ASCII alphanumeric characters.
         *     Only login and token creation responses expose this value.
         * @example 7|abcdefghijklmnopqrstuvwxyz0123456789ABCD
         */
        PlaintextToken: string;
        /**
         * @description Always the JSON null value.
         * @enum {object|null}
         */
        NullData: never | null;
        RegisterRequest: {
            /**
             * @description Username of 3–64 Unicode code points (Go runes).
             * @example imgnest-user
             */
            username: string;
            email: components["schemas"]["EmailInput"];
            password: components["schemas"]["Password"];
        };
        LoginRequest: {
            email: components["schemas"]["EmailInput"];
            password: components["schemas"]["CredentialPassword"];
        };
        PasswordRequest: {
            current_password: components["schemas"]["CredentialPassword"];
            new_password: components["schemas"]["Password"];
        };
        CreateTokenRequest: {
            /**
             * @description Token name; it must contain a non-whitespace character.
             * @example blog-client
             */
            name: string;
            /**
             * Format: date-time
             * @description Optional RFC3339 expiry later than the current time. Omitted
             *     or null means no expiry. Returned timestamps are normalized
             *     to UTC.
             * @example 2026-11-04T00:00:00Z
             */
            expires_at?: string | null;
        };
        UserView: {
            id: components["schemas"]["ID"];
            group_id: components["schemas"]["ID"];
            username: string;
            /** Format: email */
            email: string;
            /** @enum {string} */
            role: "admin" | "user";
            /** @enum {string} */
            status: "enabled" | "disabled";
            /**
             * Format: int64
             * @description Storage usage in bytes.
             */
            used_bytes: number;
            created_at: components["schemas"]["Timestamp"];
        };
        TokenView: {
            id: components["schemas"]["ID"];
            name: string;
            /** @enum {string} */
            kind: "web" | "api";
            /** @description M1 supports only the single wildcard ability ["*"]. */
            abilities: "*"[];
            expires_at: components["schemas"]["NullableTimestamp"];
            last_used_at: components["schemas"]["NullableTimestamp"];
            created_at: components["schemas"]["Timestamp"];
        };
        LoginData: {
            token: components["schemas"]["PlaintextToken"];
            user: components["schemas"]["UserView"];
            expires_at: components["schemas"]["Timestamp"];
        };
        SiteView: {
            /**
             * @description Public site title; defaults to ImgNest until a configured name exists.
             * @example ImgNest
             */
            site_name: string;
            /** @description Whether self-service registration currently accepts new users. */
            register_enabled: boolean;
        };
        PolicySummary: {
            id: components["schemas"]["ID"];
            /** @description Rule display name shown in the upload-page selector. */
            name: string;
        };
        IssuedToken: {
            token: components["schemas"]["PlaintextToken"];
            info: components["schemas"]["TokenView"];
        };
        SuccessEnvelope: {
            /** @enum {integer} */
            code: 0;
            /** @enum {string} */
            message: "ok";
            /** @description Operation-specific success payload. */
            data: unknown;
        };
        HealthEnvelope: components["schemas"]["SuccessEnvelope"] & {
            data?: {
                /** @enum {string} */
                status: "ok";
            };
        };
        UserEnvelope: components["schemas"]["SuccessEnvelope"] & {
            data?: components["schemas"]["UserView"];
        };
        LoginEnvelope: components["schemas"]["SuccessEnvelope"] & {
            data?: components["schemas"]["LoginData"];
        };
        NullEnvelope: components["schemas"]["SuccessEnvelope"] & {
            data?: components["schemas"]["NullData"];
        };
        TokenListEnvelope: components["schemas"]["SuccessEnvelope"] & {
            data?: components["schemas"]["TokenView"][];
        };
        IssuedTokenEnvelope: components["schemas"]["SuccessEnvelope"] & {
            data?: components["schemas"]["IssuedToken"];
        };
        SiteEnvelope: components["schemas"]["SuccessEnvelope"] & {
            data?: components["schemas"]["SiteView"];
        };
        PolicyListEnvelope: components["schemas"]["SuccessEnvelope"] & {
            data?: components["schemas"]["PolicySummary"][];
        };
        ErrorEnvelope: {
            /** @enum {integer} */
            code: 10001 | 10002 | 10004 | 20001 | 20002 | 20003 | 30001 | 30002 | 30003 | 30004 | 30005 | 30006 | 30007 | 50001 | 50002 | 50003;
            /** @description Human-readable error message without technical or credential details. */
            message: string;
            data: components["schemas"]["NullData"];
        };
    };
    responses: {
        /**
         * @description Native error envelope. 400/10001 invalid input; 401/20001 missing or
         *     revoked authentication; 403/20003 forbidden; 404/10001 missing image;
         *     413/10002 byte limit; 408/10004 cancellation/deadline; 429/30003 upload
         *     rate; 403/30004 quota; 409/30005 path conflict; 409/30006 in-progress
         *     image operation; 415/30007 disallowed format; 502/50002 storage failure;
         *     422/50003 processing or privacy-sanitization failure; 500/50001 other
         *     internal failure. No private source data or provider diagnostics are returned.
         */
        ImageFailure: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Invalid JSON, unknown fields, invalid path ID, or invalid input; code 10001. */
        InvalidInput: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"] & {
                    /** @enum {integer} */
                    code?: 10001;
                };
            };
        };
        /** @description Missing, malformed, expired, revoked, or otherwise invalid bearer token; code 20001. */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"] & {
                    /** @enum {integer} */
                    code?: 20001;
                };
            };
        };
        /** @description Incorrect email/password or disabled account; code 20002. */
        InvalidCredentials: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"] & {
                    /** @enum {integer} */
                    code?: 20002;
                };
            };
        };
        /** @description Token does not belong to the authenticated user or does not exist; code 20003. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"] & {
                    /** @enum {integer} */
                    code?: 20003;
                };
            };
        };
        /** @description Site registration is disabled; code 30001. */
        RegistrationDisabled: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"] & {
                    /** @enum {integer} */
                    code?: 30001;
                };
            };
        };
        /** @description Username or email is already registered; code 30002. */
        UserExists: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"] & {
                    /** @enum {integer} */
                    code?: 30002;
                };
            };
        };
        /** @description More than three registration or login requests per minute from the same client IP; code 30003. */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"] & {
                    /** @enum {integer} */
                    code?: 30003;
                };
            };
        };
        /** @description Internal operation or database health check failed; code 50001. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"] & {
                    /** @enum {integer} */
                    code?: 50001;
                };
            };
        };
    };
    parameters: {
        /** @description Authenticated native numeric image identifier. */
        ImageID: components["schemas"]["ID"];
        ImagePageNumber: number;
        ImagePageSize: number;
    };
    requestBodies: {
        ImageSelection: {
            content: {
                "application/json": {
                    ids: components["schemas"]["ImageIDs"];
                };
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Application and database are available. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthEnvelope"];
                };
            };
            503: components["responses"]["InternalError"];
        };
    };
    getSite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public site descriptor. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteEnvelope"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    listPolicies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Permitted rules for the upload-page selector. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyListEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            500: components["responses"]["InternalError"];
        };
    };
    registerUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description User created. No token is issued by registration. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEnvelope"];
                };
            };
            400: components["responses"]["InvalidInput"];
            403: components["responses"]["RegistrationDisabled"];
            409: components["responses"]["UserExists"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Credentials accepted and web token issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginEnvelope"];
                };
            };
            400: components["responses"]["InvalidInput"];
            401: components["responses"]["InvalidCredentials"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Enabled user associated with the bearer token. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            500: components["responses"]["InternalError"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current token revoked; data is null. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NullEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            500: components["responses"]["InternalError"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed and all tokens revoked; data is null. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NullEnvelope"];
                };
            };
            400: components["responses"]["InvalidInput"];
            /**
             * @description Code 20001 means the bearer token is missing or invalid.
             *     Code 20002 means the current password is incorrect.
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"] & {
                        /** @enum {integer} */
                        code?: 20001 | 20002;
                    };
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    listTokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token metadata owned by the authenticated user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenListEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            500: components["responses"]["InternalError"];
        };
    };
    createToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTokenRequest"];
            };
        };
        responses: {
            /** @description API token created, with plaintext and safe metadata. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuedTokenEnvelope"];
                };
            };
            400: components["responses"]["InvalidInput"];
            401: components["responses"]["Unauthenticated"];
            500: components["responses"]["InternalError"];
        };
    };
    revokeToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Positive signed BIGINT token identifier. */
                id: components["schemas"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Owned token revoked; data is null. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NullEnvelope"];
                };
            };
            400: components["responses"]["InvalidInput"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    uploadImages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** @description Repeat the file part for multiple images; file or files[] is required. */
                    file?: string[];
                    /** @description Alternative repeatable file-part name. */
                    "files[]"?: string[];
                    policy_id?: components["schemas"]["ID"];
                    album_id?: components["schemas"]["ID"];
                    /**
                     * @description Multipart text must be exactly true or false.
                     * @default false
                     */
                    is_public?: boolean;
                } | unknown | unknown;
            };
        };
        responses: {
            /** @description One image committed, including all declared variants. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageEnvelope"];
                };
            };
            /** @description Per-file results; inspect every item's status and code. */
            207: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageBatchEnvelope"];
                };
            };
            /** @description Request canceled or upload deadline exceeded; code 10004. */
            408: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request or file exceeds its byte limit; code 10002. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            default: components["responses"]["ImageFailure"];
        };
    };
    listImages: {
        parameters: {
            query?: {
                page?: components["parameters"]["ImagePageNumber"];
                size?: components["parameters"]["ImagePageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Image page without EXIF, source IP, or storage credentials. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImagePageEnvelope"];
                };
            };
            default: components["responses"]["ImageFailure"];
        };
    };
    getImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Authenticated native numeric image identifier. */
                id: components["parameters"]["ImageID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Image metadata without EXIF. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageEnvelope"];
                };
            };
            default: components["responses"]["ImageFailure"];
        };
    };
    trashImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Authenticated native numeric image identifier. */
                id: components["parameters"]["ImageID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Image moved to trash; data is null. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NullEnvelope"];
                };
            };
            default: components["responses"]["ImageFailure"];
        };
    };
    setImageVisibility: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Authenticated native numeric image identifier. */
                id: components["parameters"]["ImageID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    is_public: boolean;
                };
            };
        };
        responses: {
            /** @description Updated image. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageEnvelope"];
                };
            };
            default: components["responses"]["ImageFailure"];
        };
    };
    getImageExif: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Authenticated native numeric image identifier. */
                id: components["parameters"]["ImageID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Private metadata; response is not cached. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageExifEnvelope"];
                };
            };
            default: components["responses"]["ImageFailure"];
        };
    };
    batchImages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    action: "delete" | "permission";
                    ids: components["schemas"]["ImageIDs"];
                    /** @description Required for permission; must be omitted for delete. */
                    is_public?: boolean;
                };
            };
        };
        responses: {
            /** @description Per-ID status, preserving the requested ID order. */
            207: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageBatchEnvelope"];
                };
            };
            default: components["responses"]["ImageFailure"];
        };
    };
    listTrash: {
        parameters: {
            query?: {
                page?: components["parameters"]["ImagePageNumber"];
                size?: components["parameters"]["ImagePageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recycle-bin page with retained local thumbnail references. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImagePageEnvelope"];
                };
            };
            default: components["responses"]["ImageFailure"];
        };
    };
    restoreImages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ImageSelection"];
        responses: {
            /** @description Per-ID restore results; successful data is null. */
            207: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageBatchEnvelope"];
                };
            };
            default: components["responses"]["ImageFailure"];
        };
    };
    purgeImages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ImageSelection"];
        responses: {
            /** @description Per-ID purge results; successful data is null. */
            207: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageBatchEnvelope"];
                };
            };
            default: components["responses"]["ImageFailure"];
        };
    };
    getLocalImageObject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storageID: components["schemas"]["ID"];
                /** @description Canonical object key, possibly containing slash-separated path segments, with its extension. */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Raw image bytes with Content-Length and the detected image MIME type. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/*": string;
                };
            };
            /** @description Requested WebP was skipped; Location points to the stored original. */
            302: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["ImageFailure"];
        };
    };
    headLocalImageObject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storageID: components["schemas"]["ID"];
                /** @description Canonical object key, possibly containing slash-separated path segments, with its extension. */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Image headers without bytes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description WebP fallback redirect. */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["ImageFailure"];
        };
    };
    getImageThumbnail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable opaque image key, excluding the .webp suffix. */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Raw WebP thumbnail, without metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/webp": string;
                };
            };
            default: components["responses"]["ImageFailure"];
        };
    };
    headImageThumbnail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable opaque image key, excluding the .webp suffix. */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Thumbnail headers without bytes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["ImageFailure"];
        };
    };
}
