CREATE TABLE storages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    driver TEXT NOT NULL CHECK (driver IN ('local', 's3')),
    config JSONB NOT NULL ,
    base_url TEXT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    storage_id BIGINT NOT NULL REFERENCES storages(id) ON DELETE RESTRICT,
    name TEXT NOT NULL,
    path_tpl TEXT NOT NULL DEFAULT '{Y}/{m}/{d}',
    name_tpl TEXT NOT NULL DEFAULT '{uniqid}',
    webp_mode TEXT NOT NULL DEFAULT 'both' CHECK (webp_mode IN ('both', 'webp_only', 'none')),
    webp_quality INTEGER NOT NULL DEFAULT 80 CHECK (webp_quality BETWEEN 1 AND 100),
    webp_effort INTEGER NOT NULL DEFAULT 4 CHECK (webp_effort BETWEEN 0 AND 6),
    webp_lossless BOOLEAN NOT NULL DEFAULT false,
    max_width INTEGER NOT NULL DEFAULT 0 CHECK (max_width >= 0),
    max_height INTEGER NOT NULL DEFAULT 0 CHECK (max_height >= 0),
    strip_meta BOOLEAN NOT NULL DEFAULT true,
    skip_if_larger BOOLEAN NOT NULL DEFAULT true,
    thumb_enabled BOOLEAN NOT NULL DEFAULT true,
    thumb_size INTEGER NOT NULL DEFAULT 400 CHECK (thumb_size > 0),
    scrub_mode TEXT NOT NULL DEFAULT 'gps' CHECK (scrub_mode IN ('none', 'gps', 'all')),
    link_prefer TEXT NOT NULL DEFAULT 'webp' CHECK (link_prefer IN ('origin', 'original', 'webp')),
    heif_mode TEXT NOT NULL DEFAULT 'webp_only' CHECK (heif_mode IN ('webp_only', 'keep', 'reject')),
    on_conflict TEXT NOT NULL DEFAULT 'rename' CHECK (on_conflict IN ('rename', 'reject')),
    enabled BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX policies_storage_id ON policies(storage_id);

CREATE TABLE group_policies (
    group_id BIGINT NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
    policy_id BIGINT NOT NULL REFERENCES policies(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(group_id, policy_id)
);
ALTER TABLE groups ADD COLUMN default_policy_id BIGINT REFERENCES policies(id) ON DELETE SET NULL;
UPDATE groups SET max_file_bytes = 20971520, allowed_exts = '["jpg","png","gif","webp","bmp","tif","tiff","heic","avif"]',
    updated_at = CURRENT_TIMESTAMP WHERE is_default = true AND max_file_bytes = 0;

CREATE TABLE albums (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    name TEXT NOT NULL,
    intro TEXT NOT NULL DEFAULT '',
    is_public BOOLEAN NOT NULL DEFAULT false,
    cover_image_id BIGINT,
    image_count BIGINT NOT NULL DEFAULT 0 CHECK (image_count >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX albums_user_id ON albums(user_id);

CREATE TABLE images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT NOT NULL UNIQUE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    album_id BIGINT REFERENCES albums(id) ON DELETE SET NULL,
    policy_id BIGINT NOT NULL REFERENCES policies(id) ON DELETE RESTRICT,
    storage_id BIGINT NOT NULL REFERENCES storages(id) ON DELETE RESTRICT,
    path TEXT NOT NULL,
    ext TEXT NOT NULL,
    origin_name TEXT NOT NULL DEFAULT '',
    mime TEXT NOT NULL,
    src_md5 TEXT NOT NULL DEFAULT '',
    md5 TEXT NOT NULL DEFAULT '',
    sha1 TEXT NOT NULL DEFAULT '',
    ip TEXT NOT NULL DEFAULT '',
    state TEXT NOT NULL CHECK (state IN ('pending', 'active', 'trash')),
    operation TEXT NOT NULL DEFAULT '' CHECK (operation IN ('', 'upload', 'cleanup', 'trash', 'restore', 'restore_cleanup', 'purge')),
    operation_id TEXT NOT NULL,
    has_original BOOLEAN NOT NULL DEFAULT false,
    has_webp BOOLEAN NOT NULL DEFAULT false,
    has_thumb BOOLEAN NOT NULL DEFAULT false,
    scrubbed BOOLEAN NOT NULL DEFAULT false,
    is_public BOOLEAN NOT NULL DEFAULT false,
    size BIGINT NOT NULL DEFAULT 0 CHECK (size >= 0),
    webp_size BIGINT NOT NULL DEFAULT 0 CHECK (webp_size >= 0),
    thumb_bytes BIGINT NOT NULL DEFAULT 0 CHECK (thumb_bytes >= 0),
    charged_bytes BIGINT NOT NULL DEFAULT 0 CHECK (charged_bytes >= 0),
    width INTEGER NOT NULL DEFAULT 0 CHECK (width >= 0),
    height INTEGER NOT NULL DEFAULT 0 CHECK (height >= 0),
    frames INTEGER NOT NULL DEFAULT 1 CHECK (frames >= 1),
    object_manifest JSONB NOT NULL DEFAULT '[]' CHECK (jsonb_typeof(object_manifest) = 'array'),
    deleted_at TIMESTAMPTZ,
    purge_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(storage_id, path),
    CHECK (state <> 'trash' OR deleted_at IS NOT NULL)
);
CREATE INDEX images_user_state_operation ON images(user_id, state, operation);
CREATE INDEX images_purge_at ON images(state, purge_at);
CREATE INDEX images_operation ON images(operation);
ALTER TABLE albums ADD CONSTRAINT albums_cover_image_id_fkey FOREIGN KEY(cover_image_id) REFERENCES images(id) ON DELETE SET NULL;

CREATE TABLE image_exif (
    image_id BIGINT PRIMARY KEY REFERENCES images(id) ON DELETE CASCADE,
    make TEXT NOT NULL DEFAULT '',
    model TEXT NOT NULL DEFAULT '',
    lens TEXT NOT NULL DEFAULT '',
    exposure TEXT NOT NULL DEFAULT '',
    f_number TEXT NOT NULL DEFAULT '',
    focal_length TEXT NOT NULL DEFAULT '',
    iso INTEGER NOT NULL DEFAULT 0 CHECK (iso >= 0),
    orientation INTEGER NOT NULL DEFAULT 0 CHECK (orientation BETWEEN 0 AND 8),
    taken_at TIMESTAMPTZ,
    gps_lat DOUBLE PRECISION,
    gps_lng DOUBLE PRECISION,
    gps_alt DOUBLE PRECISION,
    raw JSONB NOT NULL DEFAULT '{}' ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

