-- Random image links: one anonymous redirect link per album, addressed by the
-- owner's random public id plus the link token.
ALTER TABLE users ADD COLUMN public_id TEXT;
CREATE UNIQUE INDEX users_public_id_key ON users (public_id);

CREATE TABLE random_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    album_id BIGINT NOT NULL REFERENCES albums(id) ON DELETE CASCADE,
    token TEXT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX random_links_album_id_key ON random_links (album_id);
CREATE UNIQUE INDEX random_links_token_key ON random_links (token);
CREATE INDEX random_links_user_id_idx ON random_links (user_id);
