-- External sign-in identities (OIDC / OAuth2 subjects) linked to local
-- accounts. provider is "{plugin}:{provider id}"; no profile data is copied.
CREATE TABLE user_identities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    provider TEXT NOT NULL CHECK (length(provider) BETWEEN 1 AND 80),
    subject TEXT NOT NULL CHECK (length(subject) BETWEEN 1 AND 255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (provider, subject)
);
CREATE INDEX user_identities_user_id ON user_identities (user_id);
